services:
  - type: web
    name: stockapi
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
